added frame rate calculation to AVC parser
ROCm/rocDecode pull request #307
Opened 2024-04-03 21:55 UTC by paveltc

2024-04-04 12:28 UTC, AryanSalmanpour requested changes

2024-04-04 12:28 UTC, AryanSalmanpour commented on src/parser/avc_parser.h
> +    /frame rate
Add the missing forward slash for the comment here `/frame rate` -> `//frame rate` . This causes a compilation failure in CI.

2024-04-04 12:28 UTC, AryanSalmanpour commented on src/parser/avc_parser.cpp
> +        std::cout << "DEBUG: Frame rate = " << frame_rate_calculated << " fps\n";
remove printing out the DEBUG info here. Remove both std::cout.

2024-04-04 14:42 UTC, jeffqjiangNew commented
@paveltc We need to change the code flow. Let's discuss offline.

2024-04-05 01:09 UTC, jeffqjiangNew approved these changes

2024-04-05 12:15 UTC, AryanSalmanpour approved these changes

2024-04-05 12:15 UTC, merged