videodemuxer: added seek functionality
ROCm/rocDecode pull request #311
Opened 2024-04-10 00:51 UTC by rrawther

added seek functionality to video demuxer

2024-04-10 16:04 UTC, AryanSalmanpour requested changes
@rrawther added a few minor formatting issues. Please take a look. Thanks.

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +typedef enum Seekseek_mode_enum {
change `Seekseek_mode_enum` to `SeekModeEnum`

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +}SeekMode;
add a space `}SeekMode` -> `} SeekMode`

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +typedef enum SeekCriteria_enum {
change `SeekCriteria_enum` to `SeekCriteriaEnum`

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +}SeekCriteria;
add a space  `}SeekCriteria` -> `} SeekCriteria`

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +    {
move the opening bracket to the previous line.

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +            auto const ts_sec = (double)frame_num / frame_rate_;
use `static_cast<double>(frame_num)` instead of `(double)frame_num`

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +        frame_rate_ = static_cast<double> (av_fmt_input_ctx_->streams[av_stream_]->r_frame_rate.num) / static_cast<double> (av_fmt_input_ctx_->streams[av_stream_]->r_frame_rate.den);
remove extra space between `>` and `(` in `static_cast<double> (av_fmt_input_ctx_`. Please fix all several other occurrences of the same issue in this file.

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +        case SEEK_CRITERIA_FRAME_NUM:
use 4 steps indentation for all `case`

2024-04-10 16:04 UTC, AryanSalmanpour commented on utils/video_demuxer.h
> +        case SEEK_CRITERIA_FRAME_NUM:
use 4 steps indentation for all `case`

2024-04-10 21:53 UTC, rrawther commented on utils/video_demuxer.h
> +            auto const ts_sec = (double)frame_num / frame_rate_;
done

2024-04-11 12:21 UTC, AryanSalmanpour approved these changes

2024-04-11 12:21 UTC, merged