AVC: Added support for picture adaptive frame-field (PICAFF) feature.
ROCm/rocDecode pull request #325
Opened 2024-04-29 15:13 UTC by jeffqjiangNew

* 10 more field conformance streams now pass.

2024-04-30 16:15 UTC, AryanSalmanpour requested changes

2024-04-30 16:15 UTC, AryanSalmanpour commented on src/parser/avc_parser.cpp
> +    int frame_num_wrap_1 = ((AvcVideoParser::AvcPicture*)p_pic_info_1)->frame_num_wrap;
please use c++ style cast (reinterpret_cast) for p_pic_info_1 and p_pic_info_2 on lines 2041-2042 and 2054-2055.

2024-04-30 19:49 UTC, jeffqjiangNew commented on src/parser/avc_parser.cpp
> +    int frame_num_wrap_1 = ((AvcVideoParser::AvcPicture*)p_pic_info_1)->frame_num_wrap;
This will be addressed after PR#323 is merged into develop and develop is merged into this branch.

2024-05-01 01:44 UTC, jeffqjiangNew commented on src/parser/avc_parser.cpp
> +    int frame_num_wrap_1 = ((AvcVideoParser::AvcPicture*)p_pic_info_1)->frame_num_wrap;
Develop branch merged.

2024-05-01 12:29 UTC, AryanSalmanpour approved these changes

2024-05-01 12:29 UTC, merged