AV1: VA-API submission
ROCm/rocDecode pull request #362
Opened 2024-06-04 16:55 UTC by LakshmiKumar23

2024-06-04 17:23 UTC, rrawther commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +            for (int i = 0; i < 8; i++) {
why is this 8? I thought we have 16 ref frames

2024-06-04 17:23 UTC, rrawther reviewed
Added a comment

2024-06-04 17:25 UTC, LakshmiKumar23 commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +            for (int i = 0; i < 8; i++) {
The `va_dec_av1.h` defines 8 ref frames. So I matched it with that. Is it incorrect to match with that?
```
    /** \brief Surface indices of reference frames in DPB.
     *
     *  Contains a list of uncompressed frame buffer surface indices as references.
     *  Application needs to make sure all the entries point to valid frames
     *  except for intra frames by checking ref_frame_id[]. If missing frame
     *  is identified, application may choose to perform error recovery by
     *  pointing problematic index to an alternative frame buffer.
     *  Driver is not responsible to validate reference frames' id.
     */
    VASurfaceID             ref_frame_map[8];

    /** \brief Reference frame indices.
     *
     *  Contains a list of indices into ref_frame_map[8].
     *  It specifies the reference frame correspondence.
     *  The indices of the array are defined as [LAST_FRAME – LAST_FRAME,
     *  LAST2_FRAME – LAST_FRAME, …, ALTREF_FRAME – LAST_FRAME], where each
     *  symbol is defined as:
     *  enum{INTRA_FRAME = 0, LAST_FRAME, LAST2_FRAME, LAST3_FRAME, GOLDEN_FRAME,
     *  BWDREF_FRAME, ALTREF2_FRAME, ALTREF_FRAME};
     */
    uint8_t                 ref_frame_idx[7];
```

2024-06-04 17:33 UTC, jeffqjiangNew commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +            for (int i = 0; i < 8; i++) {
8 is the max for AV1.

2024-06-04 19:37 UTC, jeffqjiangNew requested changes

2024-06-04 19:37 UTC, jeffqjiangNew commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +                    pPicParams->pic_params.av1.ref_frame_idx[i] = va_surface_ids_[pPicParams->pic_params.av1.ref_frame_idx[i]];
We should assign VA surface IDs to ref_frame_map[8], not ref_frame_idx[7]. ref_frame_idx[7] is the indices to ref_frame_map[].

2024-06-04 19:40 UTC, jeffqjiangNew requested changes

2024-06-04 19:40 UTC, jeffqjiangNew commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +            pPicParams->pic_params.av1.current_frame = curr_surface_id;
Also add surface ID for current_display_picture and anchor_frames_list as well, for future proof.

2024-06-04 22:26 UTC, jeffqjiangNew requested changes

2024-06-04 22:26 UTC, jeffqjiangNew commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +                pPicParams->pic_params.av1.current_display_picture = va_surface_ids_[pPicParams->pic_params.av1.current_display_picture];
Add a check of the index against the vector size to prevent invalid memory access.

2024-06-04 22:26 UTC, jeffqjiangNew commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +                    pPicParams->pic_params.av1.anchor_frames_list[i] = va_surface_ids_[pPicParams->pic_params.av1.anchor_frames_list[i]];
Add a check of the index against the vector size to prevent invalid memory access.

2024-06-05 00:59 UTC, jeffqjiangNew requested changes

2024-06-05 00:59 UTC, jeffqjiangNew commented on src/rocdecode/vaapi/vaapi_videodecoder.cpp
> +            if (pPicParams->pic_params.av1.anchor_frames_num != 0xFF) {
This check of frame number against 0xFF is not necessary.

2024-06-05 16:55 UTC, jeffqjiangNew approved these changes

2024-06-05 20:23 UTC, AryanSalmanpour approved these changes

2024-06-05 20:23 UTC, merged