AV1: Added OBU parsing and frame data parsing.
ROCm/rocDecode pull request #364
Opened 2024-06-06 15:12 UTC by jeffqjiangNew

2024-06-06 16:12 UTC, rrawther commented on src/parser/av1_parser.cpp
> +
remove empty line

2024-06-06 16:14 UTC, rrawther commented on src/parser/av1_parser.cpp
> +        if ((ret = ReadObuHeaderAndSize()) == PARSER_EOF ) {
probably you can change it to while (cond){ } instead and add is as part of cond.

2024-06-06 16:15 UTC, rrawther commented on src/parser/av1_parser.cpp
> +
do we need empty line here?

2024-06-06 16:19 UTC, rrawther requested changes
Added some comments.
I see the use of lots of empty lines in the code, @AryanSalmanpour: please check if this is up  to standard convention. Or else, remove un-necessary empty lines

2024-06-06 19:10 UTC, jeffqjiangNew commented on src/parser/av1_parser.cpp
> +        if ((ret = ReadObuHeaderAndSize()) == PARSER_EOF ) {
Yes. Was preparing something more complicated but now it is not needed. Done.

2024-06-06 19:10 UTC, jeffqjiangNew commented on src/parser/av1_parser.cpp
> +
Done.

2024-06-06 19:14 UTC, jeffqjiangNew commented on src/parser/av1_parser.cpp
> +
Removed.

2024-06-10 14:40 UTC, jeffqjiangNew commented
@rrawther Please take a look the latest changes.

2024-06-10 15:16 UTC, AryanSalmanpour commented on src/parser/av1_parser.cpp
> +    if (seen_frame_header_ == 1) {
Are you planning to add any code to the body of this if condition `if (seen_frame_header_ == 1) {` ? if not, 
Please change this if-else condition to an if condition only -> `if (frame_header_ > 1) {`

2024-06-10 15:21 UTC, jeffqjiangNew commented on src/parser/av1_parser.cpp
> +    if (seen_frame_header_ == 1) {
At this moment, not sure if we need to do something here (actually copy the frame header or not). Will check during bring up.

2024-06-10 15:45 UTC, rrawther approved these changes

2024-06-10 16:07 UTC, AryanSalmanpour approved these changes

2024-06-10 16:07 UTC, merged