WIP: VideoToSequence sample
ROCm/rocDecode pull request #373
Opened 2024-06-25 00:28 UTC by rrawther

Initial implementation for VideoToSequence sample
Seeking and decoding has some issues and needs to fix

2024-06-25 18:24 UTC, LakshmiKumar23 requested changes

2024-06-25 18:24 UTC, LakshmiKumar23 commented on utils/rocvideodecode/roc_video_dec.cpp
> +bool RocVideoDecoder::SetReconfigParams(ReconfigParams *p_reconfig_params, bool b_force_recofig_flush) {
Typo in `b_force_reconfig_flush`

2024-06-25 18:24 UTC, LakshmiKumar23 commented on samples/videoToSequence/CMakeLists.txt
> +# Copyright (c) 2023 - 2024 Advanced Micro Devices, Inc.
Copyright from 2024

2024-06-25 18:24 UTC, LakshmiKumar23 commented on samples/videoToSequence/README.md
> +./videodecode -i <Input file/folder Path [required]>
change to `./videotosequence` if that's the executable name

2024-06-25 18:24 UTC, LakshmiKumar23 commented on samples/videoToSequence/videotosequence.cpp
> +Copyright (c) 2023 - 2024 Advanced Micro Devices, Inc. All rights reserved.
copyright from 2024

2024-07-22 03:59 UTC, LakshmiKumar23 commented on samples/videoToSequence/videotosequence.cpp
> +#if __cplusplus >= 201703L && __has_include(<filesystem>)
@rrawther this is already added at he beginning of the file. We should not redefine. Please check

2024-07-22 04:00 UTC, LakshmiKumar23 approved these changes

2024-07-22 12:42 UTC, AryanSalmanpour approved these changes

2024-07-22 12:42 UTC, merged