Ctest - Add av1 test case
ROCm/rocDecode pull request #395
Opened 2024-07-23 18:51 UTC by LakshmiKumar23

2024-07-23 20:21 UTC, AryanSalmanpour requested changes
This is failing on CI on gfx90a. Please see [here](http://math-ci.amd.com/job/mainline/job/precheckin/job/rocDecode/job/PR-395/1/pipeline-console/?selected-node=276#:~:text=%5BERR%5D%20%20%7BrocDecParseVideoData%7D%20%20%20%7B%20HandleVideoSequence%20%7D%20rocDecGetDecoderCaps(%26decode_caps)%20returned%20ROCDEC_NOT_SUPPORTED%20at%20/opt/rocm/share/rocdecode/utils/rocvideodecode/roc_video_dec.cpp%3A288
)

2024-07-25 18:43 UTC, AryanSalmanpour requested changes

2024-07-25 18:43 UTC, AryanSalmanpour commented on utils/rocvideodecode/roc_video_dec.cpp
> +rocDecStatus RocVideoDecoder::CodecSupported(int device_id, rocDecVideoCodec codec_id, uint32_t bit_depth) {
return `bool` instead of `rocDecStatus`

2024-07-25 18:43 UTC, AryanSalmanpour commented on utils/rocvideodecode/roc_video_dec.cpp
> +    return rocDecGetDecoderCaps(&decode_caps);
return true here if the status of the `rocDecGetDecoderCaps` is `ROCDEC_SUCCESS` otherwise false

2024-07-26 15:43 UTC, LakshmiKumar23 commented
@AryanSalmanpour gfx90a with ub22 passes -- http://math-ci.amd.com/job/mainline/job/precheckin/job/rocDecode/view/change-requests/job/PR-395/5/pipeline-console/?selected-node=817

2024-07-26 16:43 UTC, AryanSalmanpour approved these changes

2024-07-26 21:09 UTC, merged